language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install:
  - ./src/main/bash/install-gumtree.sh

script:
  - mvn clean install

after_success:
  - mvn clean test jacoco:report coveralls:report
